### ISSUE TITLE
Zope 4

### ISSUE THREAD

**Issue by tech-kio** [nakagami/Products.FirebirdDA#2]
Hello,

Would it be possible to get a Zope 4.x compatible version?

It would be really appreciated!

**Comment by nakagami** [comment]
Sadly, Zope4 is still not support SQLMethod, Database Adapter and another related Products.

**Comment by tech-kio** [comment]
If you pin the version with the Beta one, it seems to work perfectly well :
[versions]
Products.ZMySQLDA=4.0b4

eggs =
    zope.sqlalchemy
    Products.ZMySQLDA
    Products.ZSQLMethods

The main problem I think, trying to install FirebirdDA, is the Threading library which does not seem to work right now.

**Comment by nakagami** [comment]
Oh, really,

Thanks, I will try it.
