### ISSUE TITLE
Broken Pipe on firebird server restart

### ISSUE THREAD

**Issue by georgpfolz** [nakagami/Products.FirebirdDA#5]
When I restart the firebird server, the connection of a FirebirdDA does not function anymore. If I do a query, I get

first, but only for a very short time:
```
Error type:  OperationalError
Message: ('Can not recv() packets', 0)
```

then:
```
Error type: BrokenPipeError
Message: (32, 'Broken pipe')
```

Closing and reopening the connection resolves the issue, but that's not a viable solution on a production machine.

I already programmed a fix for this, I have still some testing to do and will probably make the pull request tomorrow.

```
for qs in queries:
    """
    the try-except block is a workaround for an
    OperationalError or a broken pipe
    when the firebird server is restarted.
    """
    try:
        c.execute(qs)
    except BrokenPipeError as e:
        self.close()
        self.open()
        c.execute(qs)
    except OperationalError as e:
        if e.args[0] == 'Can not recv() packets':
            time.sleep(2.5)  # give it some time until it becomes a broken pipe
            self.close()
            self.open()
            c.execute(qs)
```

**Comment by georgpfolz** [comment]
That didn't work as expected, so I put I loop and a `try` around the whole content of the `query` method, so the cursor is rebuilt at each try. This works.

**Comment by georgpfolz** [comment]
I made the pull request.

**Comment by nakagami** [comment]
merged
